export const CAIO_DOMAINS = [
  { key: 'vision', name: 'Strategic Vision & CAIO Leadership', group: 'Strategic & Governance',
    frameworks: ['6-Step CAIO Implementation', 'Alignment Framework (6 dimensions)', 'Portfolio Approach'],
    questions: [
      'Is there a clear, documented AI vision aligned with organizational strategy?',
      'Has the CAIO or equivalent leadership role been defined with C-suite authority?',
      'Is there a balanced portfolio of short-term and long-term AI initiatives?',
      'Does the AI strategy connect to specific business outcomes?',
    ]},
  { key: 'governance', name: 'AI Governance Framework', group: 'Strategic & Governance',
    frameworks: ['NIST AI RMF (Govern/Map/Measure/Manage)', 'Hosanagar 3 Governance Principles', 'Harvard 8 Ethics Principles'],
    questions: [
      'Is there a formal AI governance framework (e.g., aligned with NIST AI RMF)?',
      'Are all four NIST functions operational (Govern, Map, Measure, Manage)?',
      'Is there a governance board or center of excellence with clear authority?',
      'Are governance policies documented and regularly reviewed?',
    ]},
  { key: 'ethics', name: 'Ethical AI & Responsible Innovation', group: 'Strategic & Governance',
    frameworks: ['6 Ethical AI Principles', 'Belmont Report', 'Manipulation Spectrum'],
    questions: [
      'Are all 6 ethical AI principles explicitly adopted and documented?',
      'Is there an ethics review process before deployment?',
      'Has the AI Ethics & Compliance Checklist been completed?',
    ]},
  { key: 'data', name: 'Data Strategy & Governance', group: 'Data & Fairness',
    frameworks: ['7-Component Data Governance', '5-Stage Privacy Lifecycle'],
    questions: [
      'Are all 7 data governance components implemented?',
      'Is there a centralized data architecture (not siloed)?',
      'Is data quality actively managed with defined standards?',
      'Has the 5-stage privacy lifecycle been evaluated?',
    ]},
  { key: 'fairness', name: 'Algorithmic Fairness & Bias', group: 'Data & Fairness',
    frameworks: ['Bias Sources (nature vs. nurture)', 'Fairness Trade-offs', 'Proxy Variable Detection'],
    questions: [
      'Has training data been audited for depth, diversity, and historical biases?',
      'Have proxy variables been identified and assessed?',
      'Which fairness definition is being applied, and is the trade-off documented?',
      'Are diverse teams involved in the design process?',
    ]},
  { key: 'privacy', name: 'Privacy & Data Protection', group: 'Data & Fairness',
    frameworks: ['GDPR/DPDP/CCPA', 'Federated Learning', 'Differential Privacy', 'Privacy by Design'],
    questions: [
      'Has each AI system been evaluated at all 5 privacy lifecycle stages?',
      'Is data used only for the context in which consent was given?',
      'Which legal frameworks apply, and is the system compliant?',
      'Is privacy by design practiced (not an afterthought)?',
    ]},
  { key: 'talent', name: 'AI Talent & Organizational Culture', group: 'Organization & Technology',
    frameworks: ['6-Area Competency Framework', 'Talent Mix 20/30/50', 'Three-Pillar Culture'],
    questions: [
      'Are all 6 competency areas addressed in the AI talent strategy?',
      'Is the talent mix balanced (20% specialists, 30% converted, 50% supporting)?',
      'Is there a culture of psychological safety for AI experimentation?',
    ]},
  { key: 'technology', name: 'Technology Architecture & MLOps', group: 'Organization & Technology',
    frameworks: ['Three-Tier AI Classification', 'CI/CD for AI', 'SCALE Framework', 'AI Monitoring (5 categories)'],
    questions: [
      'Are AI systems classified by tier (deterministic/probabilistic/generative)?',
      'Is CI/CD implemented for AI systems?',
      'Are all 5 monitoring categories actively tracked?',
      'Has the architecture been assessed using SCALE criteria?',
    ]},
  { key: 'portfolio', name: 'AI Project & Portfolio Management', group: 'Execution & Measurement',
    frameworks: ['5-Phase Project Framework', 'Vendor Selection (6 criteria)', 'BRIDGE Roadmap'],
    questions: [
      'Is the 5-phase project management framework followed?',
      'Is there cross-functional ownership (business/technical/product)?',
      'Has vendor selection followed a structured evaluation?',
    ]},
  { key: 'security', name: 'AI Security & Risk Management', group: 'Execution & Measurement',
    frameworks: ['NIST AI RMF Risk Functions', 'AIRS Framework', 'Adversarial Attack Surface'],
    questions: [
      'Has a comprehensive AI risk assessment been conducted?',
      'Are adversarial attack surfaces identified and mitigated?',
      'Is there an AI-specific incident response plan?',
    ]},
  { key: 'change', name: 'Implementation & Change Management', group: 'Execution & Measurement',
    frameworks: ['ADAPT Change Model (5 steps)', 'Three-Pillar Culture', 'Innovation Rituals'],
    questions: [
      'Has the ADAPT model been followed?',
      'Are there change champions at every organizational level?',
      'Are hard metrics (adoption, productivity) AND soft metrics (confidence, engagement) tracked?',
    ]},
  { key: 'measurement', name: 'Measurement & ROI', group: 'Execution & Measurement',
    frameworks: ['Metrics Pyramid', '5Q Impact Framework', 'GARD Risk Governance'],
    questions: [
      'Are leading AND lagging indicators tracked?',
      'Is the 5Q Impact Framework applied?',
      'Has the GARD risk governance process been implemented?',
      'Is there a metrics pyramid connecting operational → tactical → strategic?',
    ]},
] as const;

export const CAIO_DOMAIN_GROUPS = [
  'Strategic & Governance',
  'Data & Fairness',
  'Organization & Technology',
  'Execution & Measurement',
] as const;
