import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } from 'docx';

interface DocxSection {
  sectionName: string;
  fields: { label: string; value: string; type: string }[];
}

export async function generateDocx(
  templateName: string,
  title: string,
  sections: DocxSection[]
): Promise<Buffer> {
  const children: Paragraph[] = [];

  // Title
  children.push(new Paragraph({
    children: [new TextRun({ text: title, bold: true, size: 36, font: 'Calibri' })],
    heading: HeadingLevel.TITLE,
    alignment: AlignmentType.CENTER,
    spacing: { after: 400 },
  }));

  // Subtitle
  children.push(new Paragraph({
    children: [new TextRun({ text: `Template: ${templateName}`, size: 20, color: '666666', font: 'Calibri' })],
    alignment: AlignmentType.CENTER,
    spacing: { after: 400 },
  }));

  // Divider
  children.push(new Paragraph({
    border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: '0052cc' } },
    spacing: { after: 400 },
  }));

  // Sections
  for (const section of sections) {
    children.push(new Paragraph({
      children: [new TextRun({ text: section.sectionName, bold: true, size: 28, font: 'Calibri', color: '0052cc' })],
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 400, after: 200 },
    }));

    for (const field of section.fields) {
      if (field.type === 'checkbox') {
        children.push(new Paragraph({
          children: [
            new TextRun({ text: field.value === 'true' ? '☑ ' : '☐ ', size: 22, font: 'Calibri' }),
            new TextRun({ text: field.label, size: 22, font: 'Calibri' }),
          ],
          spacing: { after: 100 },
        }));
      } else {
        children.push(new Paragraph({
          children: [new TextRun({ text: field.label, bold: true, size: 22, font: 'Calibri' })],
          spacing: { before: 200, after: 60 },
        }));

        const valueLines = (field.value || '(not provided)').split('\n');
        for (const line of valueLines) {
          children.push(new Paragraph({
            children: [new TextRun({
              text: line,
              size: 22,
              font: 'Calibri',
              color: field.value ? '333333' : '999999',
            })],
            spacing: { after: 40 },
          }));
        }
      }
    }
  }

  // Footer
  children.push(new Paragraph({
    border: { top: { style: BorderStyle.SINGLE, size: 6, color: '0052cc' } },
    spacing: { before: 600 },
  }));
  children.push(new Paragraph({
    children: [new TextRun({
      text: `Generated by Agent Deployment Playbook · ${new Date().toLocaleDateString()} · © 2026 Padmasani Srimadhan`,
      size: 18,
      color: '999999',
      font: 'Calibri',
      italics: true,
    })],
    alignment: AlignmentType.CENTER,
  }));

  const doc = new Document({ sections: [{ children }] });
  const buffer = await Packer.toBuffer(doc);
  return buffer as Buffer;
}
