import PptxGenJS from 'pptxgenjs';

const NAVY = '0a1628';
const WHITE = 'FFFFFF';
const ACCENT = '3b82f6';
const GRAY = '94a3b8';
const COPYRIGHT = '\u00a9 2026 Padmasani Srimadhan. All rights reserved.';

interface ReportSection {
  title: string;
  items: { label: string; value: string }[];
}

function addFooter(slide: PptxGenJS.Slide) {
  slide.addText(COPYRIGHT, {
    x: 0.8, y: 5.2, w: 8.4, h: 0.2,
    fontSize: 7, fontFace: 'Calibri', color: GRAY, italic: true,
  });
}

function addHeader(slide: PptxGenJS.Slide, text: string) {
  slide.addShape('rect' as never, { x: 0, y: 0, w: 10, h: 0.7, fill: { color: NAVY } });
  slide.addText(text, {
    x: 0.8, y: 0.1, w: 8.4, h: 0.5,
    fontSize: 13, fontFace: 'Calibri', color: WHITE, bold: true,
  });
}

export async function generateProjectPptx(
  projectName: string,
  projectDescription: string,
  sections: ReportSection[],
  meta: { status: string; framework?: string; architecture?: string; createdAt: string }
): Promise<Buffer> {
  const pptx = new PptxGenJS();
  pptx.author = 'Padmasani Srimadhan';
  pptx.company = 'Agent Deployment Playbook';
  pptx.title = projectName;

  // Title Slide
  const t = pptx.addSlide();
  t.background = { color: NAVY };
  t.addText('AGENT DEPLOYMENT PLAYBOOK', {
    x: 0.8, y: 0.8, w: 8.4, h: 0.4,
    fontSize: 11, fontFace: 'Calibri', color: ACCENT, bold: true,
  });
  t.addText(projectName, {
    x: 0.8, y: 1.6, w: 8.4, h: 1.2,
    fontSize: 32, fontFace: 'Calibri', color: WHITE, bold: true,
  });
  t.addText(projectDescription || 'Project Summary Report', {
    x: 0.8, y: 3.0, w: 8.4, h: 0.6, fontSize: 14, fontFace: 'Calibri', color: GRAY,
  });
  const ml = [
    `Status: ${meta.status}`,
    meta.framework ? `Framework: ${meta.framework}` : '',
    meta.architecture ? `Pattern: ${meta.architecture}` : '',
    `Created: ${meta.createdAt}`,
  ].filter(Boolean).join('  \u00b7  ');
  t.addText(ml, { x: 0.8, y: 4.2, w: 8.4, h: 0.3, fontSize: 10, fontFace: 'Calibri', color: GRAY });
  addFooter(t);

  // Content Slides
  for (const section of sections) {
    const s = pptx.addSlide();
    s.background = { color: WHITE };
    addHeader(s, section.title.toUpperCase());
    let y = 1.0;
    for (const item of section.items) {
      if (y > 4.6) break;
      s.addText(item.label, {
        x: 0.8, y, w: 2.4, h: 0.3,
        fontSize: 10, fontFace: 'Calibri', color: ACCENT, bold: true, valign: 'top',
      });
      const lines = Math.min(Math.ceil((item.value || '\u2014').length / 90), 4);
      s.addText(item.value || '\u2014', {
        x: 3.3, y, w: 6.2, h: 0.25 * lines,
        fontSize: 10, fontFace: 'Calibri', color: '334155', valign: 'top',
      });
      y += Math.max(0.35, 0.25 * lines + 0.1);
    }
    addFooter(s);
  }

  // Closing Slide
  const c = pptx.addSlide();
  c.background = { color: NAVY };
  c.addText('End of Report', {
    x: 0.8, y: 2.0, w: 8.4, h: 0.8,
    fontSize: 28, fontFace: 'Calibri', color: WHITE, bold: true, align: 'center',
  });
  c.addText(`Generated by ADP \u00b7 ${new Date().toLocaleDateString()}`, {
    x: 0.8, y: 3.0, w: 8.4, h: 0.4,
    fontSize: 11, fontFace: 'Calibri', color: GRAY, align: 'center',
  });
  addFooter(c);

  const ab = await pptx.write({ outputType: 'arraybuffer' }) as ArrayBuffer;
  return Buffer.from(ab);
}
